name: Release on Tag

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build, test, collect artifacts and create release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build (Gradle) and run tests
        run: |
          ./gradlew clean test jacocoTestReport build

      - name: Package coverage HTML
        run: zip -r gradle-coverage-html.zip build/reports/jacoco/test/html || true

      - name: Build Maven package and tests
        run: |
          mvn -B clean test package || true

      - name: Package maven coverage HTML
        run: zip -r maven-coverage-html.zip target/site/jacoco || true

      - name: Package Gradle JAR artifacts
        run: zip -r gradle-artifacts.zip build/libs/ || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            gradle-artifacts.zip
            gradle-coverage-html.zip
            target/*.jar
            maven-coverage-html.zip
